### PR TITLE
Pathfinding Improvements

### PR DESCRIPTION
**Pull request by JordanL2**
Fixed issues with pathfinding which causes mobs to walk into walls and get stuck. Seems to be working a lot better now with the A* and theta pathfinding at least (I've not touched the neighbors or obstacle_avoidance methods).

### Pathfinding Improvements

mob_meta.get_node_height:
Moved to pathfinding, and made public (creatura.get_node_height).
Now uses collision box rather than node box, if available, unless flag specifies not to.
Fix for getting node height for nodes with connected node boxes

pathfinding.get_ground_level:
We now have one copy between pathfinding and mob_meta.
Can check a larger range of nodes at different heights.
Takes into account node height of both target node, and the height of the node we're coming from.

pathfinding.get_neighbors:
Get maximum distance mob can travel up/down from mob stepheight.
Improved checking diagonals are clear.
Improved checking vertical clearance, takes into account height of current and target node.
Vertical clearance can cope with nodes that have a different collision and node boxes, like snow.
Vertical clearance has a tiny height adjustment so a 2 node heigh entity can fit through a 2 node gap.
Fixed bug where it was assumed a node was reachable if it's the end goal.

methods.movement_theta_pathfind and movement_pathfind:
Fixed bug that raised goal pos by 0.5 nodes.

### Movement Improvements

Pathfinding movement functions for A* and theta have been combined into one generic function.
Ensure next goal is always set if there is a valid path.
Checking if mob has reached the next goal improved - now works no matter the mob height, and the height of the node below the goal.
Mobs now won't overshoot their goal, if they're very close to it (less than mob width) their speed reduces.
The more a mob is turning, the less forward velocity it has. This should fix spinning a lot.

mob:pos_in_box now can take a size param that is a table, containing the separate width and height.

pathfinding.moveable no longer pads an extra 0.2 around the width of mob when checking if there is sufficient space for the mob.

pathfinding.get_neighbors now uses max_fall for the maximum distance we can go down, instead of stepheight.

### CODE REVIEW

**Comment by ElCeejo** [comment]
Did some testing and found that it breaks mob following behavior in Animalia. Spawn in some cows and hold wheat, they just walk in somewhat of a circle. Pretty sure this has to do with the changes to pathfinding movement methods.

**Comment by JordanL2** [comment]
Fixed, the vertical check on the pos_in_box should be correct now, no matter the node its standing on too.

Also the movement should be better in general, at least less susceptible to spinning. The more the mob has to turn, the less forward velocity it has. If it has to turn at full turning speed, the forward velocity drops to zero. This means it won't circle the position it's aiming for.

**Comment by ElCeejo** [comment]
First issue I've found is that pathfinding.moveable padding by 0.2 isn't a bug. It does so because of an issue with indexing positions without the padding. Sorry for not getting to this sooner btw, been busy with some visual assets.

**Comment by JordanL2** [comment]
I can add it back in, but would you mind explaining what you mean by indexing positions and the issue without the padding?

**Comment by ElCeejo** [comment]
Best explained through screenshots.

The particle represent the indexed positions of a Dragons hitbox with the + 0.2 padding
screenshot_20220320_035821

and this is without the padding.
screenshot_20220320_035845

I have no idea why this happens, but not having the padding is definitely a potential issue for bigger mobs.

**Comment by JordanL2** [comment]
Is this to do with `index_box_border` in mob_meta.lua?

**Comment by ElCeejo** [comment]
Nope, index_box_border just grabs each node around the based of a mobs collisionbox but doesn't modify anything. I encountered this same issue with mobkit as well, so I don't think any lua-side tampering is to blame.

**Comment by JordanL2** [comment]
Odd, as far as I can see, `pathfinder.moveable` is only used in `pathfinder.get_neighbors`.

**Comment by ElCeejo** [comment]
It is, but it's very important because it checks if the mobs entire collisionbox can fit at each neighboring position.

**Comment by JordanL2** [comment]
I'll add it back, also found an issue with dragons pathfinding around snow, will fix that too.

**Comment by JordanL2** [comment]
I've increased the mob's collision box vertically when we're checking if the next pathfinding goal is inside the box, this helps dragons. The fire dragon seems to have trouble pathfinding around its own fire, although that seems to be an existing issue (shouldn't fire be seen as non-walkable?).

**Pull request closed without merging**
